/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AkiliCreditsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COST_CHAT_MESSAGE"
      | "COST_GD_ANALYSIS"
      | "COST_WALLET_AUDIT"
      | "COST_WALLET_REPORT"
      | "GD"
      | "agent"
      | "canAfford"
      | "deposit"
      | "depositors"
      | "getCredits"
      | "globalTotalDeposited"
      | "globalTotalSpent"
      | "owner"
      | "setAgent"
      | "spendCredits"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposited" | "Spent" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COST_CHAT_MESSAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COST_GD_ANALYSIS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COST_WALLET_AUDIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COST_WALLET_REPORT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GD", values?: undefined): string;
  encodeFunctionData(functionFragment: "agent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canAfford",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getCredits", values: [string]): string;
  encodeFunctionData(
    functionFragment: "globalTotalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalTotalSpent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spendCredits",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COST_CHAT_MESSAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COST_GD_ANALYSIS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COST_WALLET_AUDIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COST_WALLET_REPORT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canAfford", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCredits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTotalSpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spendCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    userKey: BytesLike,
    from: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    userKey: string,
    from: string,
    amount: bigint,
    newBalance: bigint
  ];
  export interface OutputObject {
    userKey: string;
    from: string;
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpentEvent {
  export type InputTuple = [
    userKey: BytesLike,
    action: string,
    cost: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [
    userKey: string,
    action: string,
    cost: bigint,
    remaining: bigint
  ];
  export interface OutputObject {
    userKey: string;
    action: string;
    cost: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    userKey: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [userKey: string, to: string, amount: bigint];
  export interface OutputObject {
    userKey: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AkiliCredits extends BaseContract {
  connect(runner?: ContractRunner | null): AkiliCredits;
  waitForDeployment(): Promise<this>;

  interface: AkiliCreditsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COST_CHAT_MESSAGE: TypedContractMethod<[], [bigint], "view">;

  COST_GD_ANALYSIS: TypedContractMethod<[], [bigint], "view">;

  COST_WALLET_AUDIT: TypedContractMethod<[], [bigint], "view">;

  COST_WALLET_REPORT: TypedContractMethod<[], [bigint], "view">;

  GD: TypedContractMethod<[], [string], "view">;

  agent: TypedContractMethod<[], [string], "view">;

  canAfford: TypedContractMethod<
    [userId: string, action: string],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<
    [userId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositors: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getCredits: TypedContractMethod<
    [userId: string],
    [
      [bigint, bigint, bigint, boolean] & {
        balance: bigint;
        totalDeposited: bigint;
        totalSpent: bigint;
        canAffordReport: boolean;
      }
    ],
    "view"
  >;

  globalTotalDeposited: TypedContractMethod<[], [bigint], "view">;

  globalTotalSpent: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  spendCredits: TypedContractMethod<
    [userId: string, action: string],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [userId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COST_CHAT_MESSAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COST_GD_ANALYSIS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COST_WALLET_AUDIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COST_WALLET_REPORT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "GD"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canAfford"
  ): TypedContractMethod<[userId: string, action: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [userId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositors"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCredits"
  ): TypedContractMethod<
    [userId: string],
    [
      [bigint, bigint, bigint, boolean] & {
        balance: bigint;
        totalDeposited: bigint;
        totalSpent: bigint;
        canAffordReport: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalTotalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalTotalSpent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spendCredits"
  ): TypedContractMethod<
    [userId: string, action: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [userId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Spent"
  ): TypedContractEvent<
    SpentEvent.InputTuple,
    SpentEvent.OutputTuple,
    SpentEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(bytes32,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Spent(bytes32,string,uint256,uint256)": TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
    Spent: TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;

    "Withdrawn(bytes32,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
