/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AkiliLog {
  export type DecisionStruct = {
    agent: AddressLike;
    userHash: BytesLike;
    action: string;
    timestamp: BigNumberish;
  };

  export type DecisionStructOutput = [
    agent: string,
    userHash: string,
    action: string,
    timestamp: bigint
  ] & { agent: string; userHash: string; action: string; timestamp: bigint };
}

export interface AkiliLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decisionCount"
      | "decisions"
      | "getDecision"
      | "getUserStats"
      | "isAgent"
      | "logDecision"
      | "logGDClaimAlert"
      | "owner"
      | "setAgent"
      | "userDecisionCount"
      | "userLastActivityAt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentSet" | "DecisionLogged" | "GDClaimAlertSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "decisionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logDecision",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "logGDClaimAlert",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "userDecisionCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLastActivityAt",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "decisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "logDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logGDClaimAlert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDecisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLastActivityAt",
    data: BytesLike
  ): Result;
}

export namespace AgentSetEvent {
  export type InputTuple = [agent: AddressLike, allowed: boolean];
  export type OutputTuple = [agent: string, allowed: boolean];
  export interface OutputObject {
    agent: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecisionLoggedEvent {
  export type InputTuple = [
    agent: AddressLike,
    userHash: BytesLike,
    action: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    userHash: string,
    action: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agent: string;
    userHash: string;
    action: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GDClaimAlertSentEvent {
  export type InputTuple = [
    userHash: BytesLike,
    idleDays: BigNumberish,
    gdBalance: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userHash: string,
    idleDays: bigint,
    gdBalance: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userHash: string;
    idleDays: bigint;
    gdBalance: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AkiliLog extends BaseContract {
  connect(runner?: ContractRunner | null): AkiliLog;
  waitForDeployment(): Promise<this>;

  interface: AkiliLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decisionCount: TypedContractMethod<[], [bigint], "view">;

  decisions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        agent: string;
        userHash: string;
        action: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDecision: TypedContractMethod<
    [index: BigNumberish],
    [AkiliLog.DecisionStructOutput],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [userId: string],
    [[bigint, bigint] & { totalDecisions: bigint; lastActivityAt: bigint }],
    "view"
  >;

  isAgent: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  logDecision: TypedContractMethod<
    [userId: string, action: string],
    [void],
    "nonpayable"
  >;

  logGDClaimAlert: TypedContractMethod<
    [userId: string, idleDays: BigNumberish, gdBalance: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAgent: TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  userDecisionCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  userLastActivityAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decisionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        agent: string;
        userHash: string;
        action: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [index: BigNumberish],
    [AkiliLog.DecisionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [userId: string],
    [[bigint, bigint] & { totalDecisions: bigint; lastActivityAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logDecision"
  ): TypedContractMethod<
    [userId: string, action: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logGDClaimAlert"
  ): TypedContractMethod<
    [userId: string, idleDays: BigNumberish, gdBalance: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userDecisionCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userLastActivityAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "AgentSet"
  ): TypedContractEvent<
    AgentSetEvent.InputTuple,
    AgentSetEvent.OutputTuple,
    AgentSetEvent.OutputObject
  >;
  getEvent(
    key: "DecisionLogged"
  ): TypedContractEvent<
    DecisionLoggedEvent.InputTuple,
    DecisionLoggedEvent.OutputTuple,
    DecisionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "GDClaimAlertSent"
  ): TypedContractEvent<
    GDClaimAlertSentEvent.InputTuple,
    GDClaimAlertSentEvent.OutputTuple,
    GDClaimAlertSentEvent.OutputObject
  >;

  filters: {
    "AgentSet(address,bool)": TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;
    AgentSet: TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;

    "DecisionLogged(address,bytes32,string,uint256)": TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;
    DecisionLogged: TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;

    "GDClaimAlertSent(bytes32,uint256,string,uint256)": TypedContractEvent<
      GDClaimAlertSentEvent.InputTuple,
      GDClaimAlertSentEvent.OutputTuple,
      GDClaimAlertSentEvent.OutputObject
    >;
    GDClaimAlertSent: TypedContractEvent<
      GDClaimAlertSentEvent.InputTuple,
      GDClaimAlertSentEvent.OutputTuple,
      GDClaimAlertSentEvent.OutputObject
    >;
  };
}
