/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AkiliEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "USDT"
      | "cancel"
      | "createOrder"
      | "execute"
      | "executor"
      | "getOrderIds"
      | "orders"
      | "owner"
      | "setExecutor"
      | "userOrders"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorUpdated"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "executor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOrderIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
}

export namespace ExecutorUpdatedEvent {
  export type InputTuple = [newExecutor: AddressLike];
  export type OutputTuple = [newExecutor: string];
  export interface OutputObject {
    newExecutor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    user: AddressLike,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    targetRate: BigNumberish,
    currency: string
  ];
  export type OutputTuple = [
    orderId: string,
    user: string,
    token: string,
    recipient: string,
    amount: bigint,
    targetRate: bigint,
    currency: string
  ];
  export interface OutputObject {
    orderId: string;
    user: string;
    token: string;
    recipient: string;
    amount: bigint;
    targetRate: bigint;
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExecutedEvent {
  export type InputTuple = [orderId: BytesLike, executedRate: BigNumberish];
  export type OutputTuple = [orderId: string, executedRate: bigint];
  export interface OutputObject {
    orderId: string;
    executedRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AkiliEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AkiliEscrow;
  waitForDeployment(): Promise<this>;

  interface: AkiliEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  createOrder: TypedContractMethod<
    [
      token: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      targetRate: BigNumberish,
      currency: string
    ],
    [string],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [orderId: BytesLike, currentRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  executor: TypedContractMethod<[], [string], "view">;

  getOrderIds: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        recipient: string;
        amount: bigint;
        targetRate: bigint;
        currency: string;
        executed: boolean;
        cancelled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setExecutor: TypedContractMethod<
    [_executor: AddressLike],
    [void],
    "nonpayable"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      token: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      targetRate: BigNumberish,
      currency: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [orderId: BytesLike, currentRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOrderIds"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        recipient: string;
        amount: bigint;
        targetRate: bigint;
        currency: string;
        executed: boolean;
        cancelled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setExecutor"
  ): TypedContractMethod<[_executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "ExecutorUpdated"
  ): TypedContractEvent<
    ExecutorUpdatedEvent.InputTuple,
    ExecutorUpdatedEvent.OutputTuple,
    ExecutorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExecuted"
  ): TypedContractEvent<
    OrderExecutedEvent.InputTuple,
    OrderExecutedEvent.OutputTuple,
    OrderExecutedEvent.OutputObject
  >;

  filters: {
    "ExecutorUpdated(address)": TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;
    ExecutorUpdated: TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;

    "OrderCancelled(bytes32)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(bytes32,address,address,address,uint256,uint256,string)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderExecuted(bytes32,uint256)": TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;
    OrderExecuted: TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;
  };
}
