/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as akiliCreditsSol from "./AkiliCredits.sol";
export type { akiliCreditsSol };
import type * as policyRouterSol from "./PolicyRouter.sol";
export type { policyRouterSol };
export type { AkiliEscrow } from "./AkiliEscrow";
export type { AkiliLog } from "./AkiliLog";
export type { MockERC20 } from "./MockERC20";
