/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AkiliCredits__factory } from "./AkiliCredits__factory";
export { IERC20__factory } from "./IERC20__factory";
